# 数据操作

In [3]:
import torch
print(torch.__version__)

1.3.1


## 1.创建tensor

In [4]:
# 未初始化的矩阵
x1 = torch.empty(3, 4)
print(x1)

# 随机tensor
x2 = torch.rand(3, 4)
print(x2)

# long全为0的tensor
x3 = torch.zeros(3, 4, dtype=torch.long)
print(x3)

# 自定义数据的tensor
x = torch.tensor([9, 1.2])
print(x)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[0.3243, 0.0356, 0.7333, 0.7358],
        [0.3917, 0.5830, 0.9686, 0.7210],
        [0.3198, 0.0188, 0.8198, 0.9032]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([9.0000, 1.2000])


### 用现有的tensor创建

In [5]:
# 返回的tensor默认具有相同的torch.dtype 和torch.device
x1 = x1.new_ones(3, 4, dtype=torch.float64)   
print(x1)

x2 = x2.new_zeros(3, 4, dtype=torch.float64) 
print(x2)

# 创建一个和原来x1一样大小的tensor，指定新的数据类型,
x = torch.randn_like(x1, dtype=torch.float)
print(x)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], dtype=torch.float64)
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]], dtype=torch.float64)
tensor([[-1.0766, -0.7888,  0.5984, -1.3196],
        [ 0.0095,  1.1953, -1.1500, -1.0287],
        [ 0.5114,  1.3904, -1.9649, -2.3372]])


### 获取tensor形状

In [6]:
print(x.size())
print(x.shape)

torch.Size([3, 4])
torch.Size([3, 4])


## 2、操作

### 算术操作

In [7]:
# 加法1
y = torch.rand(3, 4)
print(x + y)

# 加法2
print(torch.add(x, y))

# 指定输出
res = torch.empty(3, 4)
torch.add(x , y, out=res)
print(res)

# 加法3, inplace版本，后面有后缀_
y.add_(x)
print(y)



tensor([[-0.3810, -0.6470,  1.3744, -1.1333],
        [ 0.5150,  1.4616, -0.1797, -0.4077],
        [ 0.5679,  1.9079, -1.1252, -2.2883]])
tensor([[-0.3810, -0.6470,  1.3744, -1.1333],
        [ 0.5150,  1.4616, -0.1797, -0.4077],
        [ 0.5679,  1.9079, -1.1252, -2.2883]])
tensor([[-0.3810, -0.6470,  1.3744, -1.1333],
        [ 0.5150,  1.4616, -0.1797, -0.4077],
        [ 0.5679,  1.9079, -1.1252, -2.2883]])
tensor([[-0.3810, -0.6470,  1.3744, -1.1333],
        [ 0.5150,  1.4616, -0.1797, -0.4077],
        [ 0.5679,  1.9079, -1.1252, -2.2883]])


### 索引

索引出来的结果与原数据共享内存，也即修改一个，另一个会跟着修改。
pytorch中还有一些函数，提供索引选择数据，如：index_select(input, dim, index)、masked_select(input, mask)、nonzero(input)、gather(input, dim, index)等

In [9]:
y = x[0, :]
print(y)
y += 1
print(y)
print(x[0, :])  # 原来的tensor也被修改了

tensor([-0.0766,  0.2112,  1.5984, -0.3196])
tensor([0.9234, 1.2112, 2.5984, 0.6804])
tensor([0.9234, 1.2112, 2.5984, 0.6804])


### 改变形状

In [11]:
y = x.view(12)  # 3*4=12
z = x.view(-1 , 4)  # -1所指的维度可以根据其他维度的值推出来
print(x.size(), y.size(), z.size())

torch.Size([3, 4]) torch.Size([12]) torch.Size([3, 4])


In [12]:
# view仅仅是改变了对这个张量的观察角度，内部数据并未改变
x += 1
print(x)
print(y) # 也增加1

tensor([[ 1.9234,  2.2112,  3.5984,  1.6804],
        [ 1.0095,  2.1953, -0.1500, -0.0287],
        [ 1.5114,  2.3904, -0.9649, -1.3372]])
tensor([ 1.9234,  2.2112,  3.5984,  1.6804,  1.0095,  2.1953, -0.1500, -0.0287,
         1.5114,  2.3904, -0.9649, -1.3372])


In [13]:
# 想返回一个真正新的副本，reshape()可以改变形状，但是此函数并不能保证返回的是其拷贝，所以不推荐使用。推荐先用clone创造一个副本然后再使用view

x_cp = x.clone().view(12)
x -= 1
print(x)
print(x_cp)

tensor([[ 0.9234,  1.2112,  2.5984,  0.6804],
        [ 0.0095,  1.1953, -1.1500, -1.0287],
        [ 0.5114,  1.3904, -1.9649, -2.3372]])
tensor([ 1.9234,  2.2112,  3.5984,  1.6804,  1.0095,  2.1953, -0.1500, -0.0287,
         1.5114,  2.3904, -0.9649, -1.3372])


### 数据转换
将一个标量Tensor转换成一个Python number

In [14]:
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.8220])
0.8220337629318237


### tensor与numpy相互转换
1、tensor 转 numpy


In [15]:
a = torch.ones(5)
b = a.numpy()
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)


tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


2、NumPy数组转Tensor: from-numpy

In [18]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a, b)

a += 1
print(a, b)
b += 1
print(a, b)


[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


### tensor on GPU

In [ ]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, dexice=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))    # to()还可以同时更改数据类型 